# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rech_cv_interface.ui',
# licensing of 'rech_cv_interface.ui' applies.
#
# Created: Tue Sep  3 16:18:18 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 830)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_rech = QtWidgets.QLabel(self.centralwidget)
        self.lbl_rech.setMouseTracking(False)
        self.lbl_rech.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_rech.setAcceptDrops(False)
        self.lbl_rech.setAutoFillBackground(False)
        self.lbl_rech.setObjectName("lbl_rech")
        self.verticalLayout_3.addWidget(self.lbl_rech)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_rech = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rech.setDragEnabled(False)
        self.lineEdit_rech.setObjectName("lineEdit_rech")
        self.horizontalLayout_4.addWidget(self.lineEdit_rech)
        self.pb_lancer_rech = QtWidgets.QPushButton(self.centralwidget)
        self.pb_lancer_rech.setObjectName("pb_lancer_rech")
        self.horizontalLayout_4.addWidget(self.pb_lancer_rech)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_cv_entree = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cv_entree.setObjectName("lbl_cv_entree")
        self.verticalLayout.addWidget(self.lbl_cv_entree)
        self.listW_cv_entree = QtWidgets.QListWidget(self.centralwidget)
        self.listW_cv_entree.setDragDropOverwriteMode(False)
        self.listW_cv_entree.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.listW_cv_entree.setObjectName("listW_cv_entree")
        self.verticalLayout.addWidget(self.listW_cv_entree)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_bouton_add = QtWidgets.QLabel(self.centralwidget)
        self.lbl_bouton_add.setObjectName("lbl_bouton_add")
        self.horizontalLayout_2.addWidget(self.lbl_bouton_add)
        self.pb_ajouter = QtWidgets.QPushButton(self.centralwidget)
        self.pb_ajouter.setObjectName("pb_ajouter")
        self.horizontalLayout_2.addWidget(self.pb_ajouter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pb_enlever = QtWidgets.QPushButton(self.centralwidget)
        self.pb_enlever.setObjectName("pb_enlever")
        self.horizontalLayout_3.addWidget(self.pb_enlever)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_cv_sortie = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cv_sortie.setObjectName("lbl_cv_sortie")
        self.verticalLayout_2.addWidget(self.lbl_cv_sortie)
        self.listW_cv_sortie = QtWidgets.QListWidget(self.centralwidget)
        self.listW_cv_sortie.setObjectName("listW_cv_sortie")
        self.verticalLayout_2.addWidget(self.listW_cv_sortie)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_efacer_liste = QtWidgets.QLabel(self.centralwidget)
        self.lbl_efacer_liste.setObjectName("lbl_efacer_liste")
        self.horizontalLayout_5.addWidget(self.lbl_efacer_liste)
        self.pb_effacer_liste = QtWidgets.QPushButton(self.centralwidget)
        self.pb_effacer_liste.setObjectName("pb_effacer_liste")
        self.horizontalLayout_5.addWidget(self.pb_effacer_liste)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lbl_rech.setText(QtWidgets.QApplication.translate("MainWindow", "Recherche :", None, -1))
        self.lineEdit_rech.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Entrez les mots clés de votre recherche", None, -1))
        self.pb_lancer_rech.setText(QtWidgets.QApplication.translate("MainWindow", "Go", None, -1))
        self.lbl_cv_entree.setText(QtWidgets.QApplication.translate("MainWindow", "Liste des CV sur lesquels la recherche sera effectuée :", None, -1))
        self.lbl_bouton_add.setText(QtWidgets.QApplication.translate("MainWindow", "Ajouter un CV : ", None, -1))
        self.pb_ajouter.setText(QtWidgets.QApplication.translate("MainWindow", "Ajouter", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Supprimer CV selectionné :", None, -1))
        self.pb_enlever.setText(QtWidgets.QApplication.translate("MainWindow", "Enlever", None, -1))
        self.lbl_cv_sortie.setText(QtWidgets.QApplication.translate("MainWindow", "Liste des CV contenant les mots clef correspondant :", None, -1))
        self.lbl_efacer_liste.setText(QtWidgets.QApplication.translate("MainWindow", "Efface la liste des cv : ", None, -1))
        self.pb_effacer_liste.setText(QtWidgets.QApplication.translate("MainWindow", "Effacer", None, -1))

